### ISSUE TITLE
SetFixes Extra Suggestions 

### ISSUE THREAD

**Issue by RinMaru** [supercoolsonic/SADXDC-SET-Layout-Fixes#1]
## Twinkle Park
 I think the Extra Flower pots could go in they look nice and add to the scene.

## Final Egg
The secret room (With some goodies that is) and the wooden looking thing for the tower in Final egg would be cool aswell i'd be happy to test them.

## Egg Carrier
Once the mod loader has the ability to use submods I think you could definitely add back in those other things you did. and they would be togglable

**Comment by Thesch28** [comment]
With other things do you mean the laundry machine and beta stuff? I also want some of that stuff

**Comment by Zetchzie** [comment]
By other things I mean he had it to where any character could transform the ship and access the captions room once you beat the characters story

**Comment by Thesch28** [comment]
I want that too.

**Comment by supercoolsonic** [comment]
I now have a lot more free time to work on this project. I will begin preparing the SET Fixes + Extras mod tomorrow, and would be happy to include some of your suggestions. However, could I have some clarity on the Final Egg object you're talking about? What object number is it?

**Comment by Zetchzie** [comment]
the circular ring you said was possibly used as a ceiling for objects like cameras

**Comment by Zetchzie** [comment]
![fe1](https://cloud.githubusercontent.com/assets/15071652/25974535/9bbb96da-3677-11e7-9fa3-f12d1be30eef.png)

**Comment by supercoolsonic** [comment]
Ah, that. Sure thing. I'll work on integrating the flower pots into the level for Sonic, Big, and Amy in a way that doesn't feel too intrusive, I'll add both rings to Act 2 in Final Egg, and open up the Captain's room for everyone. I'll release the mod tomorrow once I'm sure I got all straightened out. For now, you can much on this if you're interested. I've made more progress in making it feel like the original.
http://www.filedropper.com/oldwindyvalley
I "restored" a few more objects, added some tweaks to make it feel like a finished level, and there's quite a few texture updates.

**Comment by Zetchzie** [comment]
Ah nice I love Beta Windyvally

**Comment by supercoolsonic** [comment]
First version of SET Fixes + Extras has been released! Check out the changelog on the Releases page to learn more about what's new.

**Comment by Darkspines147** [comment]
Hey, PkR told me to bring this up with you since your modifying the SETs. Any chance at replicating the Level design of the original Japanese version, like the unsyncronized spiketraps in Lost World?

**Comment by supercoolsonic** [comment]
Oooh.....what an excellent idea. I'll try looking into that soon.

**Comment by Thesch28** [comment]
Apparently there is an error with the Set files on station square there are a lot objects from twinkle park and all the collision to enter other sections is gone here's a picture.
http://i.imgur.com/SNwXbrs.png
Also there is something that says Act Twinkle Only.

**Comment by Darkspines147** [comment]
They are probably coded as individual objects, despite being one model. The game was rushed to market for Christmas after all. That, or maybe the model was intended to behave the way it does in DX, so the Original SA may have had bugged code that gave off the effect of de-syncnization. Those are a couple of theories.

If it can't be done, I'm sorry for wasting your time. You say you have access to the ingame files? That's farther than I could get, all the programs I had access to crashed, I was trying to get the files for the camera from that version, I would love to have those, what programs are you using?

**Comment by supercoolsonic** [comment]
@Thesch28 It's been fixed, and you can download it in the Release section.

@Darkspines147 They're actually each an individual object. They're just lined up in a row in the snake room. In the wall panel room in Act 2, you can see them not in a row. I don't think the de-synchronization was a bug. The horizontal moving spike traps in Act 2 in Knuckles' level are de-synchronized, but they have different variables from each other. The ones in the snake room do not, even in the Japanese version. Yet they fall differently than the international versions. So I have no idea what makes them do that. I'm sorry.
You want the camera files for the Japanese version?
http://www.megafileupload.com/1qmt0/Sonic_Adventure_Japanese_Camera_Files.7z
Enjoy.

**Comment by Darkspines147** [comment]
That may be the only way to replicate it, by modifying the variables...

I am having no luck downloading from that website...

**Comment by supercoolsonic** [comment]
You shouldn't need to make an account for that. At least, for the slow download, anyway.

**Comment by Darkspines147** [comment]
I clicked it, and the website just hung up, nothing I clicked afterwards would work in that window. For some reason MSEdge just would not respond, I got a much faster result just signing up for a free account, but the site also seems to not have a dedicated "Delete Account" button, which is why I don't like sites like that. Also Media Fire and MEGA.nz offer the same sevices for free users that MFU offers it's premium members. I'll probably delete this and the last post I made, as it's a severely off-topic discussion for a Suggestions thread...

Thank you for the files, you really didn't have to do that for me.

**Comment by Thesch28** [comment]
I Think it would be cool to have a JP Dreamcast Camera Mod.

**Comment by supercoolsonic** [comment]
http://www.megafileupload.com/2Mhog/Japanese_Camera.7z
I don't think it restores the camera angles in cutscenes, though.
And let's try to stat on-topic here, OK?

**Comment by Darkspines147** [comment]
It doesn't, those scenes would have to be completely remade from scratch.

**Comment by supercoolsonic** [comment]
Built? The mod for Japanese Cameras? It's in the link I just posted.

**Comment by Darkspines147** [comment]
I made it a SADX Mod loader mod, just after I got them downloaded, I may have used the wrong term to descibe what I did, sorry...

**Comment by supercoolsonic** [comment]
It's fine. But seriously, stay on-topic for this thread. This is for suggestions for the SET Fixes + Extras mod.  Please make a separate issue thread to talk about other things that involve the SET Fixes mods, OK?

**Comment by Darkspines147** [comment]
To foloow your request to stay on topic, I removed all of my posts, they were bogging down eveything anyway.

**Comment by supercoolsonic** [comment]
I'd say the ones about the spikes in Lost World were fair enough. I'm still very confused about those, though. I wonder if PkR would be willing to look at that. It's definitely a coding difference. It just has to be.

**Comment by Darkspines147** [comment]
Considering PkR sent me straight to you when I asked on ModDB, I'd say that PkR's interested, but doesn't know how to go about it yet.

**Comment by supercoolsonic** [comment]
Well, since PkR asked you to ask me, he might've thought it was a layout difference, like with their variables. But it turned out not to be so, so I don't know if he knows that it's probably a coding thing.

**Comment by Zetchzie** [comment]
you what would be cool. adding fish into emerald coast and using bigs layout for scenery in sonic emerald coast

**Comment by supercoolsonic** [comment]
@RinMaru I'd love to add additional scenery to that area, but that's not something that can be done with SET modifications. Best ask PkR or someone else if you want that.

**Comment by supercoolsonic** [comment]
I have a test layout in the TODO issue for the automated Sky Deck Act 1 section. If you'd like to test it, you can download it there.

**Comment by supercoolsonic** [comment]
@Darkspines147 Could I talk to you about something, please? I need help with something.

**Comment by Darkspines147** [comment]
@supercoolsonic Sure. What's up?

**Comment by supercoolsonic** [comment]
Okay, you're the same Darkspines147 that extracted the autodemo Windy Valley landtables first over on the Retro forums, right?

**Comment by Darkspines147** [comment]
Sinple mistake. I made my Darkspines147 account on Xbox Live around the same time he joined Retro. I have talked with him though. Darkspines35 goes by "ItsEasyActually" on most other Social Media. Same goes for SonicFreak94, he goes by "Morph" or Retro.

**Comment by RinMaru** [comment]
I know ItsEastActually I chat with him on twitter allot lol

**Comment by Darkspines147** [comment]
I think he (SonicFreak94) is busy with the SADX Mod Loader updates as of late, so maybe he doesn't have time to check that? I've been following the Dreamcast Models Mod for a while (I don't have a twitter, though). I'm hoping it will result in a new generation of SADX Model Mods, as the old CHRMODELS.dll method has been dead for some time.

**Comment by supercoolsonic** [comment]
Ah. ...Oh, well. I guess I'll just have to wait to hear back from Dude. I've been working on something big for a few weeks, and needed help extracting some model data from a .bin file.

**Comment by Darkspines147** [comment]
https://youtu.be/dtb7rswRquk?t=1021
Not sure if I should make this a new issue or post it here, tell me if I do... I think it makes more sense to put it here, as I'm suggesting something from an older build.

I was watching the Tokyo International Forum Presentation and noticed Lost World had Arrow Shooters in the starting chamber.

**Comment by supercoolsonic** [comment]
Oh. Thank you for posting that. I just noticed something BIG. No, not the cat. Pay attention to the effect that appears when Sonic runs through the water stream in the Jungle. It's the 'Ripple' texture found in the Autodemo! It's an early version of the effect that is used in the final! Sweet, now we know what that was for.

Anyway, Darkspines147, the beta Lost World indeed had arrow shooters in the first room. They're present in the Autodemo layout, too. If you'd like, I can post a "translated" layout of the beta Act 1 here, as well as Act 2. Just using the raw layout from the Autodemo will result in many objects being wrong, so I had to correct them. Someone else did it as well, and you can see the video they made of it by googling it or something. As for adding them to the SET Fixes + Extras mod, I'll consider it if others want them in too.

**Comment by Darkspines147** [comment]
Whoa, I certainly didn't notice that! It seems SA1 was going to be far more complex than it ended up being.

Yeah, I know the video your talking about. JmTsHaW (now SPEEPSHighway, for some reason?) posted a video of the raw layout from the autodemo running in SADXPC back in 2014, with a download of those SET files. https://www.youtube.com/watch?v=Kqxo-ZS2tNs 

I know I'd certainly would love to see them back in! 

People are probably thinking "WTF is up with this guys' obseesion with the Mystic Ruins?"

**Comment by supercoolsonic** [comment]
I've created a new issue thread for the big project I'm working on. You can check it out if you'd like:
https://github.com/supercoolsonic/SADXDC-SET-Layout-Fixes/issues/7

**Comment by RinMaru** [comment]
Mystic ruins can be restored PkR has fixed the cutscene data
