### ISSUE TITLE
Emerald Coast Mission 9

### ISSUE THREAD

**Issue by PiKeyAr** [supercoolsonic/SADXDC-SET-Layout-Fixes#10]
Hi,
I've seen reports that DC Emerald Coast Act 2 is incompatible with Sonic's Mission 9. Looks like there are 3 invisible walls preventing Sonic from going through the waterfall when trying to get the balloon. It can be fixed by removing the 3 invisible walls at the following coordinates:
-474.67, 839.99, -2044.67
-405.23, 839.99, -2009.16
-277.67, 839.99, -1970.13
I've updated the DC_EmeraldCoast mod but I think the SET Fixes mod also needs this update.

**Comment by supercoolsonic** [comment]
Oops. Sorry I didn't notice this sooner. I've updated the release with fixed layouts for EC Act 2. Those walls have been removed. Let me know if it works fine.
