### ISSUE TITLE
SET Fixes in new DC Conversion mod

### ISSUE THREAD

**Issue by PiKeyAr** [supercoolsonic/SADXDC-SET-Layout-Fixes#11]
Hi,

I wanted to share some news regarding SET Fixes implementation in the new version of the Dreamcast package. There are several major changes regarding how the mod works:

Sometime soon there will be a new release of Dreamcast Conversion, which will come as a single mod with lots of configurable options (HD GUI and Sound Overhaul will remain separate, but everything else will be integrated). The SET Fixes can also be integrated into the main mod with a config option to enable or disable them. If I proceed with the integration, the fixes themselves will be in the mod's system folder, but their filenames will be SETxxxxx_S.BIN instead of SETxxxxx.BIN. This approach is beneficial because there will be less mods to mess with and mod order won't matter anymore. However, the integration will also make it impossible to update the fixes through your repo, and control over updates will go back to me again.

While this is unfortunate, I think it's the right step to take toward streamlining the mod structure, and if you want to update the SET fixes you can create an issue on my tracker like it was set up originally and post your fixes there, which I will include in the mod.

There's also a possibility to add the "SET Fixes + Extras" mod into the main package with the ability to toggle between "normal" and "extra" SET fixes. Anyway let me know what you think about this. I've already implemented the "normal" fixes as an option in the mod, but if you prefer to have the fixes as a separate mod I can reverse the integration.

**Comment by supercoolsonic** [comment]
I noticed this going on over on your Twitter. It's perfectly fine to integrate the mod as you described, with the layouts having different file names. I'm unlikely to return to the SET Fixes mod until after the Hacking Contest this year in November. My attention is locked onto the new Beta Windy Valley mod. Once that project is finished, I'll likely take a short break from porting the Autodemo stages over with ItsEasyActually, and finish up that old To-Do list for the SET Fixes mod. You can also include the '+ Extras' variant as a configurable option if you wish. Once I'm done with this project, I'll set up something like what was going on before migrating to my own repo on your repo, unless some other method is thought up of in the meantime.
