### ISSUE TITLE
Lost World - Emerald Issues

### ISSUE THREAD

**Issue by Zetchzie** [supercoolsonic/SADXDC-SET-Layout-Fixes#3]
Emerald Shards have a tendency to Spawn in places impossible to get to. Just now had one spawn underground where the circle of rings are near Knuckles spawning point. Even tikal disappears into the ground when leading you to it

**Comment by supercoolsonic** [comment]
Odd. Never had anything like that happen to me before. Like, ever. Could it have been inside a Leon that fell beneath the floor? Or were you actually able to see the emerald shard with debug mode below the floor?

**Comment by Zetchzie** [comment]
might have been a leon under the floor because if i stood still the radar would fade to yellow then red back and forth

**Comment by Zetchzie** [comment]
SADXFE seems to have fixed Leon issues

**Comment by supercoolsonic** [comment]
Yes, it did. :) They appear much more often, now. If it happens again, feel free to open this topic again. But until then, I can only assume the problem has been resolved.
