### ISSUE TITLE
Draw Distance Enhancements?

### ISSUE THREAD

**Issue by Zetchzie** [supercoolsonic/SADXDC-SET-Layout-Fixes#5]
Since this would go into sets and types of modifications I think it would be cool to increase the distance at which objects show up so that we dont have floating objects in the distance and less pop ins

For example this
![dadosrlxgaasjtr](https://cloud.githubusercontent.com/assets/15071652/26434570/6cd06b38-40d7-11e7-9df1-17f05ba488dd.jpg)

**Comment by supercoolsonic** [comment]
I don't think SET modifications will do much good in terms of draw-distance. That's handled by the sonicdx file that should be in the same folder as your .exe, and code. I've seen this "limit-break" mod that drastically increases the draw distance, but couldn't find a download. I'd talk to SonicFreak94 about that. Not much I can do.
