### ISSUE TITLE
Request to update item location in Station Square sewers

### ISSUE THREAD

**Issue by PiKeyAr** [supercoolsonic/SADXDC-SET-Layout-Fixes#9]
Hi there,

I've been editing cutscene data recently and I was able to restore the camera used in the cutscene where Sonic gets the Light Speed Shoes. The camera is hardcoded to center around the location of the powerup item, which was moved in SADX. 

The only SET file change necessary for the restored cutscene camera is the location of the LevelItem in ADVSS02.BIN, which should be 505, -92.6, 800 instead of 505, -91.9, 858. I will be pushing an update for the Station Square mod, which will restore the item's location and the cutscene camera, but it would be nice to have this in the SET Fixes mod as well.

**Comment by supercoolsonic** [comment]
Consider it done. Would provide the individual file first and then update SETFixes, but Megaupload doesn't want to connect for me. :P 
It's in the release now. Just download the release.

**Comment by PiKeyAr** [comment]
Looks good, thank you!
